### ISSUE TITLE
Deprecate Redis output

### ISSUE THREAD

**Issue by tsg** [elastic/libbeat#145] opened 2015-10-14 11:09 UTC
As we'll have Lumberjack in beta4, we should mark the Redis output as deprecated and remove it from the sample configuration files.

**Comment by tsg** [comment] 2015-10-19 11:39
Related to #160.

**Comment by monicasarbu** [comment] 2015-10-19 11:42
Duplicate of https://github.com/elastic/libbeat/issues/160

**Closed** 2015-10-19 11:42 UTC
Labels: 1.0.0-beta4, docs
